// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v6.30.0
// source: api/proto/bustracking.proto

package bustracking

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Type определяет тип транспортного средства
type Transport_Type int32

const (
	Transport_BUS        Transport_Type = 0 // Автобус
	Transport_TROLLEYBUS Transport_Type = 1 // Троллейбус
	Transport_TRAMWAY    Transport_Type = 2 // Трамвай
	Transport_MINIBUS    Transport_Type = 3 // Маршрутное такси
)

// Enum value maps for Transport_Type.
var (
	Transport_Type_name = map[int32]string{
		0: "BUS",
		1: "TROLLEYBUS",
		2: "TRAMWAY",
		3: "MINIBUS",
	}
	Transport_Type_value = map[string]int32{
		"BUS":        0,
		"TROLLEYBUS": 1,
		"TRAMWAY":    2,
		"MINIBUS":    3,
	}
)

func (x Transport_Type) Enum() *Transport_Type {
	p := new(Transport_Type)
	*p = x
	return p
}

func (x Transport_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Transport_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_bustracking_proto_enumTypes[0].Descriptor()
}

func (Transport_Type) Type() protoreflect.EnumType {
	return &file_api_proto_bustracking_proto_enumTypes[0]
}

func (x Transport_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Transport_Type.Descriptor instead.
func (Transport_Type) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_bustracking_proto_rawDescGZIP(), []int{4, 0}
}

// GPSData содержит информацию о местоположении транспортного средства.
// Используется для передачи GPS-данных.
type GPSData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`               // Идентификатор ТС в системе, которая ретранслирует GPS-данные
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`   // Широта в градусах
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"` // Долгота в градусах
	Speed         uint32                 `protobuf:"varint,4,opt,name=speed,proto3" json:"speed,omitempty"`          // Скорость в км/ч
	Course        uint32                 `protobuf:"varint,5,opt,name=course,proto3" json:"course,omitempty"`        // Курс в градусах
	Time          *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=time,proto3" json:"time,omitempty"`             // Время получения данных
	Source        string                 `protobuf:"bytes,7,opt,name=source,proto3" json:"source,omitempty"`         // Источник данных
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GPSData) Reset() {
	*x = GPSData{}
	mi := &file_api_proto_bustracking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPSData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPSData) ProtoMessage() {}

func (x *GPSData) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bustracking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPSData.ProtoReflect.Descriptor instead.
func (*GPSData) Descriptor() ([]byte, []int) {
	return file_api_proto_bustracking_proto_rawDescGZIP(), []int{0}
}

func (x *GPSData) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *GPSData) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GPSData) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GPSData) GetSpeed() uint32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *GPSData) GetCourse() uint32 {
	if x != nil {
		return x.Course
	}
	return 0
}

func (x *GPSData) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *GPSData) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

// IngestGPSDataResponse представляет ответ на прием GPS-данных.
type IngestGPSDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestGPSDataResponse) Reset() {
	*x = IngestGPSDataResponse{}
	mi := &file_api_proto_bustracking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestGPSDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestGPSDataResponse) ProtoMessage() {}

func (x *IngestGPSDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bustracking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestGPSDataResponse.ProtoReflect.Descriptor instead.
func (*IngestGPSDataResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_bustracking_proto_rawDescGZIP(), []int{1}
}

// BusTrackingInfo содержит полную информацию о транспортном средстве на маршруте.
// Включает GPS-данные, информацию о маршруте, транспорте и расписании.
type BusTrackingInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GpsData       *GPSData               `protobuf:"bytes,1,opt,name=gps_data,json=gpsData,proto3" json:"gps_data,omitempty"` // Данные о местоположении
	Route         *Route                 `protobuf:"bytes,2,opt,name=route,proto3" json:"route,omitempty"`                    // Информация о маршруте
	Transport     *Transport             `protobuf:"bytes,3,opt,name=transport,proto3" json:"transport,omitempty"`            // Информация о транспортном средстве
	Schedule      *Schedule              `protobuf:"bytes,4,opt,name=schedule,proto3" json:"schedule,omitempty"`              // Информация о расписании
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BusTrackingInfo) Reset() {
	*x = BusTrackingInfo{}
	mi := &file_api_proto_bustracking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BusTrackingInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusTrackingInfo) ProtoMessage() {}

func (x *BusTrackingInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bustracking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusTrackingInfo.ProtoReflect.Descriptor instead.
func (*BusTrackingInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_bustracking_proto_rawDescGZIP(), []int{2}
}

func (x *BusTrackingInfo) GetGpsData() *GPSData {
	if x != nil {
		return x.GpsData
	}
	return nil
}

func (x *BusTrackingInfo) GetRoute() *Route {
	if x != nil {
		return x.Route
	}
	return nil
}

func (x *BusTrackingInfo) GetTransport() *Transport {
	if x != nil {
		return x.Transport
	}
	return nil
}

func (x *BusTrackingInfo) GetSchedule() *Schedule {
	if x != nil {
		return x.Schedule
	}
	return nil
}

// Route содержит информацию о маршруте общественного транспорта.
// Включает номера маршрутов для различных картографических сервисов.
type Route struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        string                 `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`               // Номер маршрута в расписании
	Yandex        string                 `protobuf:"bytes,2,opt,name=yandex,proto3" json:"yandex,omitempty"`               // Номер маршрута для "Яндекс.Карты"
	TwoGis        string                 `protobuf:"bytes,3,opt,name=two_gis,json=twoGis,proto3" json:"two_gis,omitempty"` // Номер маршрута для "2ГИС"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_api_proto_bustracking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bustracking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_api_proto_bustracking_proto_rawDescGZIP(), []int{3}
}

func (x *Route) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *Route) GetYandex() string {
	if x != nil {
		return x.Yandex
	}
	return ""
}

func (x *Route) GetTwoGis() string {
	if x != nil {
		return x.TwoGis
	}
	return ""
}

// Transport содержит информацию о транспортном средстве.
// Включает идентификаторы и тип транспорта.
type Transport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`                                  // Уникальный идентификатор ТС в системе ретрансляции GPS-данных
	StateNumber   string                 `protobuf:"bytes,2,opt,name=state_number,json=stateNumber,proto3" json:"state_number,omitempty"` // Государственный номер транспортного средства
	Type          Transport_Type         `protobuf:"varint,3,opt,name=type,proto3,enum=Transport_Type" json:"type,omitempty"`             // Тип транспортного средства
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transport) Reset() {
	*x = Transport{}
	mi := &file_api_proto_bustracking_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transport) ProtoMessage() {}

func (x *Transport) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bustracking_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transport.ProtoReflect.Descriptor instead.
func (*Transport) Descriptor() ([]byte, []int) {
	return file_api_proto_bustracking_proto_rawDescGZIP(), []int{4}
}

func (x *Transport) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Transport) GetStateNumber() string {
	if x != nil {
		return x.StateNumber
	}
	return ""
}

func (x *Transport) GetType() Transport_Type {
	if x != nil {
		return x.Type
	}
	return Transport_BUS
}

// Schedule содержит информацию о расписании работы транспортного средства на маршруте.
// Определяет временной интервал работы ТС на конкретном маршруте.
type Schedule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        string                 `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`                              // Номер маршрута (соответствует Route.number)
	StateNumber   string                 `protobuf:"bytes,2,opt,name=state_number,json=stateNumber,proto3" json:"state_number,omitempty"` // Государственный номер ТС (соответствует Transport.state_number)
	From          *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=From,proto3" json:"From,omitempty"`                                  // Время начала работы на маршруте
	To            *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=To,proto3" json:"To,omitempty"`                                      // Время окончания работы на маршруте
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schedule) Reset() {
	*x = Schedule{}
	mi := &file_api_proto_bustracking_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schedule) ProtoMessage() {}

func (x *Schedule) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bustracking_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schedule.ProtoReflect.Descriptor instead.
func (*Schedule) Descriptor() ([]byte, []int) {
	return file_api_proto_bustracking_proto_rawDescGZIP(), []int{5}
}

func (x *Schedule) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *Schedule) GetStateNumber() string {
	if x != nil {
		return x.StateNumber
	}
	return ""
}

func (x *Schedule) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *Schedule) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

// StreamBusDataRequest представляет запрос на получение потока данных о транспортных средствах.
// В текущей реализации не содержит полей.
type StreamBusDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamBusDataRequest) Reset() {
	*x = StreamBusDataRequest{}
	mi := &file_api_proto_bustracking_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamBusDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamBusDataRequest) ProtoMessage() {}

func (x *StreamBusDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bustracking_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamBusDataRequest.ProtoReflect.Descriptor instead.
func (*StreamBusDataRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_bustracking_proto_rawDescGZIP(), []int{6}
}

var File_api_proto_bustracking_proto protoreflect.FileDescriptor

var file_api_proto_bustracking_proto_rawDesc = string([]byte{
	0x0a, 0x1b, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x75, 0x73, 0x74,
	0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xcb,
	0x01, 0x0a, 0x07, 0x47, 0x50, 0x53, 0x44, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08,
	0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67,
	0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x6c, 0x6f, 0x6e,
	0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x63, 0x6f,
	0x75, 0x72, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04,
	0x74, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x17, 0x0a, 0x15,
	0x49, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x47, 0x50, 0x53, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xa5, 0x01, 0x0a, 0x0f, 0x42, 0x75, 0x73, 0x54, 0x72, 0x61,
	0x63, 0x6b, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x23, 0x0a, 0x08, 0x67, 0x70, 0x73,
	0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x47, 0x50,
	0x53, 0x44, 0x61, 0x74, 0x61, 0x52, 0x07, 0x67, 0x70, 0x73, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1c,
	0x0a, 0x05, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e,
	0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x05, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x28, 0x0a, 0x09,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x09, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x25, 0x0a, 0x08, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75,
	0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x64,
	0x75, 0x6c, 0x65, 0x52, 0x08, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x22, 0x50, 0x0a,
	0x05, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x16,
	0x0a, 0x06, 0x79, 0x61, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x79, 0x61, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x77, 0x6f, 0x5f, 0x67, 0x69,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x77, 0x6f, 0x47, 0x69, 0x73, 0x22,
	0xa2, 0x01, 0x0a, 0x09, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69,
	0x64, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x65, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x12, 0x23, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x39, 0x0a, 0x04, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x07, 0x0a, 0x03, 0x42, 0x55, 0x53, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x52,
	0x4f, 0x4c, 0x4c, 0x45, 0x59, 0x42, 0x55, 0x53, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x54, 0x52,
	0x41, 0x4d, 0x57, 0x41, 0x59, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x4d, 0x49, 0x4e, 0x49, 0x42,
	0x55, 0x53, 0x10, 0x03, 0x22, 0xa1, 0x01, 0x0a, 0x08, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x73, 0x74, 0x61, 0x74, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x2e, 0x0a, 0x04,
	0x46, 0x72, 0x6f, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x2a, 0x0a, 0x02,
	0x54, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x54, 0x6f, 0x22, 0x16, 0x0a, 0x14, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x42, 0x75, 0x73, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x32, 0x8d, 0x01, 0x0a, 0x12, 0x42, 0x75, 0x73, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x33, 0x0a, 0x0d, 0x49, 0x6e, 0x67, 0x65, 0x73,
	0x74, 0x47, 0x50, 0x53, 0x44, 0x61, 0x74, 0x61, 0x12, 0x08, 0x2e, 0x47, 0x50, 0x53, 0x44, 0x61,
	0x74, 0x61, 0x1a, 0x16, 0x2e, 0x49, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x47, 0x50, 0x53, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x12, 0x42, 0x0a, 0x15,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x42, 0x75, 0x73, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e,
	0x67, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x15, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x42, 0x75,
	0x73, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x42,
	0x75, 0x73, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x30, 0x01,
	0x42, 0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62,
	0x61, 0x72, 0x73, 0x34, 0x33, 0x72, 0x75, 0x2f, 0x62, 0x75, 0x73, 0x32, 0x6d, 0x61, 0x70, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x62, 0x75, 0x73, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x3b,
	0x62, 0x75, 0x73, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
})

var (
	file_api_proto_bustracking_proto_rawDescOnce sync.Once
	file_api_proto_bustracking_proto_rawDescData []byte
)

func file_api_proto_bustracking_proto_rawDescGZIP() []byte {
	file_api_proto_bustracking_proto_rawDescOnce.Do(func() {
		file_api_proto_bustracking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_bustracking_proto_rawDesc), len(file_api_proto_bustracking_proto_rawDesc)))
	})
	return file_api_proto_bustracking_proto_rawDescData
}

var file_api_proto_bustracking_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_bustracking_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_proto_bustracking_proto_goTypes = []any{
	(Transport_Type)(0),           // 0: Transport.Type
	(*GPSData)(nil),               // 1: GPSData
	(*IngestGPSDataResponse)(nil), // 2: IngestGPSDataResponse
	(*BusTrackingInfo)(nil),       // 3: BusTrackingInfo
	(*Route)(nil),                 // 4: Route
	(*Transport)(nil),             // 5: Transport
	(*Schedule)(nil),              // 6: Schedule
	(*StreamBusDataRequest)(nil),  // 7: StreamBusDataRequest
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_api_proto_bustracking_proto_depIdxs = []int32{
	8,  // 0: GPSData.time:type_name -> google.protobuf.Timestamp
	1,  // 1: BusTrackingInfo.gps_data:type_name -> GPSData
	4,  // 2: BusTrackingInfo.route:type_name -> Route
	5,  // 3: BusTrackingInfo.transport:type_name -> Transport
	6,  // 4: BusTrackingInfo.schedule:type_name -> Schedule
	0,  // 5: Transport.type:type_name -> Transport.Type
	8,  // 6: Schedule.From:type_name -> google.protobuf.Timestamp
	8,  // 7: Schedule.To:type_name -> google.protobuf.Timestamp
	1,  // 8: BusTrackingService.IngestGPSData:input_type -> GPSData
	7,  // 9: BusTrackingService.StreamBusTrackingInfo:input_type -> StreamBusDataRequest
	2,  // 10: BusTrackingService.IngestGPSData:output_type -> IngestGPSDataResponse
	3,  // 11: BusTrackingService.StreamBusTrackingInfo:output_type -> BusTrackingInfo
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_proto_bustracking_proto_init() }
func file_api_proto_bustracking_proto_init() {
	if File_api_proto_bustracking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_bustracking_proto_rawDesc), len(file_api_proto_bustracking_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_bustracking_proto_goTypes,
		DependencyIndexes: file_api_proto_bustracking_proto_depIdxs,
		EnumInfos:         file_api_proto_bustracking_proto_enumTypes,
		MessageInfos:      file_api_proto_bustracking_proto_msgTypes,
	}.Build()
	File_api_proto_bustracking_proto = out.File
	file_api_proto_bustracking_proto_goTypes = nil
	file_api_proto_bustracking_proto_depIdxs = nil
}
