// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.0
// source: api/proto/bustracking.proto

package bustracking

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BusTrackingService_IngestGPSData_FullMethodName         = "/BusTrackingService/IngestGPSData"
	BusTrackingService_StreamBusTrackingInfo_FullMethodName = "/BusTrackingService/StreamBusTrackingInfo"
)

// BusTrackingServiceClient is the client API for BusTrackingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BusTrackingService предоставляет API для работы с данными о местоположении транспортных средств.
// Сервис позволяет получать GPS-данные и обогащенные данные с информацией о маршрутах и расписании.
type BusTrackingServiceClient interface {
	// IngestGPSData принимает поток GPS-данных от транспортных средств.
	// Данные включают координаты, скорость, курс и время.
	IngestGPSData(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[GPSData, IngestGPSDataResponse], error)
	// StreamBusTrackingInfo возвращает поток обогащенных данных о транспортных средствах.
	// Включает информацию о маршруте, типе транспорта и расписании.
	StreamBusTrackingInfo(ctx context.Context, in *StreamBusDataRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BusTrackingInfo], error)
}

type busTrackingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBusTrackingServiceClient(cc grpc.ClientConnInterface) BusTrackingServiceClient {
	return &busTrackingServiceClient{cc}
}

func (c *busTrackingServiceClient) IngestGPSData(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[GPSData, IngestGPSDataResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BusTrackingService_ServiceDesc.Streams[0], BusTrackingService_IngestGPSData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GPSData, IngestGPSDataResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BusTrackingService_IngestGPSDataClient = grpc.ClientStreamingClient[GPSData, IngestGPSDataResponse]

func (c *busTrackingServiceClient) StreamBusTrackingInfo(ctx context.Context, in *StreamBusDataRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BusTrackingInfo], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BusTrackingService_ServiceDesc.Streams[1], BusTrackingService_StreamBusTrackingInfo_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamBusDataRequest, BusTrackingInfo]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BusTrackingService_StreamBusTrackingInfoClient = grpc.ServerStreamingClient[BusTrackingInfo]

// BusTrackingServiceServer is the server API for BusTrackingService service.
// All implementations must embed UnimplementedBusTrackingServiceServer
// for forward compatibility.
//
// BusTrackingService предоставляет API для работы с данными о местоположении транспортных средств.
// Сервис позволяет получать GPS-данные и обогащенные данные с информацией о маршрутах и расписании.
type BusTrackingServiceServer interface {
	// IngestGPSData принимает поток GPS-данных от транспортных средств.
	// Данные включают координаты, скорость, курс и время.
	IngestGPSData(grpc.ClientStreamingServer[GPSData, IngestGPSDataResponse]) error
	// StreamBusTrackingInfo возвращает поток обогащенных данных о транспортных средствах.
	// Включает информацию о маршруте, типе транспорта и расписании.
	StreamBusTrackingInfo(*StreamBusDataRequest, grpc.ServerStreamingServer[BusTrackingInfo]) error
	mustEmbedUnimplementedBusTrackingServiceServer()
}

// UnimplementedBusTrackingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBusTrackingServiceServer struct{}

func (UnimplementedBusTrackingServiceServer) IngestGPSData(grpc.ClientStreamingServer[GPSData, IngestGPSDataResponse]) error {
	return status.Errorf(codes.Unimplemented, "method IngestGPSData not implemented")
}
func (UnimplementedBusTrackingServiceServer) StreamBusTrackingInfo(*StreamBusDataRequest, grpc.ServerStreamingServer[BusTrackingInfo]) error {
	return status.Errorf(codes.Unimplemented, "method StreamBusTrackingInfo not implemented")
}
func (UnimplementedBusTrackingServiceServer) mustEmbedUnimplementedBusTrackingServiceServer() {}
func (UnimplementedBusTrackingServiceServer) testEmbeddedByValue()                            {}

// UnsafeBusTrackingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BusTrackingServiceServer will
// result in compilation errors.
type UnsafeBusTrackingServiceServer interface {
	mustEmbedUnimplementedBusTrackingServiceServer()
}

func RegisterBusTrackingServiceServer(s grpc.ServiceRegistrar, srv BusTrackingServiceServer) {
	// If the following call panics, it indicates UnimplementedBusTrackingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BusTrackingService_ServiceDesc, srv)
}

func _BusTrackingService_IngestGPSData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BusTrackingServiceServer).IngestGPSData(&grpc.GenericServerStream[GPSData, IngestGPSDataResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BusTrackingService_IngestGPSDataServer = grpc.ClientStreamingServer[GPSData, IngestGPSDataResponse]

func _BusTrackingService_StreamBusTrackingInfo_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamBusDataRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BusTrackingServiceServer).StreamBusTrackingInfo(m, &grpc.GenericServerStream[StreamBusDataRequest, BusTrackingInfo]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BusTrackingService_StreamBusTrackingInfoServer = grpc.ServerStreamingServer[BusTrackingInfo]

// BusTrackingService_ServiceDesc is the grpc.ServiceDesc for BusTrackingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BusTrackingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "BusTrackingService",
	HandlerType: (*BusTrackingServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "IngestGPSData",
			Handler:       _BusTrackingService_IngestGPSData_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamBusTrackingInfo",
			Handler:       _BusTrackingService_StreamBusTrackingInfo_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/bustracking.proto",
}
